### ISSUE TITLE
[BUG] 'software bug' crash upon entering a new dungeon level

### ISSUE THREAD

**Issue by Cryomaniac13** [hengband/hengband#4734] opened 2024-12-16 06:07 UTC
## Version/platform

-Beta 22, English version (but I also tested it on Japanese build and managed to reproduce it)
-Windows build

## Details

Game can randomly crash with a 'software bug' popup when you enter first level of Yeek Cave (could happen with dungeon levels in general as well, didn't test further). 

When you reload your savefile after the crash, your character will be placed on the dungeon level, but you won't be standing on stairs.
Here's what it says upon attempting to load the crashed save:
![reloading](https://github.com/user-attachments/assets/cb2ef8ec-dafa-41ad-a72f-d7c15f82eeef)

## How to reproduce

This crash seems to happen at random, but going down/up Yeek Cave staircase eventually triggered it for me. 

I have a savefile with my character standing on the staircase, and I guess its current RNG value makes going down trigger the crash. (You have to go down immediately after loading the save file - waiting a turn makes the crash not happen)

[crash.zip](https://github.com/user-attachments/files/18145463/crash.zip)

**Comment by Hourier** [comment] 2024-12-16 08:55
Thank you for the report.
Now we're investigating the cause.
When we fix the issue, we'll let you know it via this ticket.
Please wait for a while.

**Comment by Hourier** [comment] 2024-12-16 13:04
The issue seems to be fixed.
Please re-check the behavior when v3.0.1.23-Beta is released.
I close this ticket once.

**Closed by Hourier** 2024-12-16 13:04 UTC

**Comment by Cryomaniac13** [comment] 2024-12-19 04:08
Tested on beta23, everything works properly now; bug fixed.
